CREATE TABLE [dbo].[info] (
    [Id]                 INT            IDENTITY (1, 1) NOT NULL,
    [fac]                VARCHAR (50)   NULL,
    [dom]                VARCHAR (50)   NULL,
    [spec]               VARCHAR (50)   NULL,
    [data]               DATE           NULL,
    [form_invat]         VARCHAR (50)   NULL,
    [nume_prenume]       VARCHAR (50)   NULL,
    [cod_legitimatie]    VARCHAR (50)   NULL,
    [localitate]         VARCHAR (50)   NULL,
    [judet]              VARCHAR (50)   NULL,
    [tara]               VARCHAR (50)   NULL,
    [strada]             VARCHAR (50)   NULL,
    [numar]              INT            NULL,
    [bloc]               VARCHAR (50)   NULL,
    [scara]              VARCHAR (50)   NULL,
    [etaj]               INT            NULL,
    [apartament]         INT            NULL,
    [sector]             INT            NULL,
    [cod_postal]         INT            NULL,
    [data_n]             DATE           NULL,
    [loc_nastere]        VARCHAR (50)   NULL,
    [judet_n]            VARCHAR (50)   NULL,
    [tara_n]             VARCHAR (50)   NULL,
    [sexul]              VARCHAR (50)   NULL,
    [stare_civila]       VARCHAR (50)   NULL,
    [cetatenie]          VARCHAR (50)   NULL,
    [cetatenie_op]       VARCHAR (50)   NULL,
    [etnie]              VARCHAR (50)   NULL,
    [incadrare]          VARCHAR (50)   NULL,
    [cnp]                VARCHAR (13)   NULL,
    [serie]              VARCHAR (2)    NULL,
    [numar_cnp]          VARCHAR (6)    NULL,
    [eliberat_de_catre]  VARCHAR (50)   NULL,
    [data_eliberare]     DATE           NULL,
    [studii]             VARCHAR (50)   NULL,
    [unitate_invatamant] VARCHAR (50)   NULL,
    [specializare]       VARCHAR (50)   NULL,
    [oras_studii]        VARCHAR (50)   NULL,
    [judet_studii]       VARCHAR (50)   NULL,
    [tara_studii]        VARCHAR (50)   NULL,
    [forma_invatamant]   VARCHAR (50)   NULL,
    [media]              VARCHAR(5) NULL,
    [durata_studii] INT NULL, 
    [data_absolvirii] DATE NULL, 
    [tipul_diploma] VARCHAR(50) NULL, 
    [serie_diploma] VARCHAR(10) NULL, 
    [numar_diploma] INT NULL, 
    PRIMARY KEY CLUSTERED ([Id] ASC)
);

